### PR TITLE
Add helpers module

### PR DESCRIPTION
**Pull request by faemmi**
Dear HBP-team,

I have used pyunicore a lot in the past and have had quite a few pieces of code that I used repetitively and thought they might fit into a package. However, I did not want to make my separate package and thus opened a PR here.

The PR is not complete yet, but you can already give your thoughts about this.

I put my code into an additional `pyunicore.helpers` module to not break the current API but just provide a supplementing API. Basically, most of the code just wraps some of the functionality you provide in `pyunicore.client` and abstracts some functionalities (almost like you describe them in the README).

## Current features
- A `dataclasses.dataclass` for the job description ([`pyunicore.helpers.requests.job_description.JobDescription`](https://github.com/faemmi/pyunicore/blob/9c021997241ac1a34145cccf77dc99e5341ea34c/pyunicore/helpers/requests/job_description.py#L16): 
  - The current API allows submitting a job to `pyunicore.client.Client.new_job` as a `dict`. I felt this is quite fragile and prone to typos. The dataclass can be constructed as usual and then passed to the `new_job` method as `job_description.to_dict()`.
  - As a side effect, this dataclass provides all possible configuration that is given by the UNICORE REST API and does not require the user to look it up on the web, but in the source code. The docstring of the dataclass just represents the API documentation.
- A class [`pyunicore.helpers.job_status.JobStatus`](https://github.com/faemmi/pyunicore/blob/9c021997241ac1a34145cccf77dc99e5341ea34c/pyunicore/helpers/job_status.py#L1) that provides all possible job status the API may return.
- Methods
  - [`pyunicore.helpers.connect.transport.create_transport`](https://github.com/faemmi/pyunicore/blob/9c021997241ac1a34145cccf77dc99e5341ea34c/pyunicore/helpers/connect/transport.py#L9) to create a transport by just providing user and password without having to encode the user and password.
  -  [`pyunicore.helpers.connect.site.connect_to_site`](https://github.com/faemmi/pyunicore/blob/9c021997241ac1a34145cccf77dc99e5341ea34c/pyunicore/helpers/connect/registry.py#L12) to connect to a site without having to create a `pyunicore.client.Transport` etc. It just requires the site API URL and user/password.
  - [`pyunicore.helpers.connect.registry.connect_to_site_from_registry`](https://github.com/faemmi/pyunicore/blob/9c021997241ac1a34145cccf77dc99e5341ea34c/pyunicore/helpers/connect/registry.py#L12) to connect to a specific site of a registry, e.g. JUWELS. It just requires the URL to the registry, user, password, and the name of the site to connect to.

## Planned features
- A dataclass for submitting a workflow definition, similar to that of the job description.

## Other notes
- I also wrote tests for the code, but I saw that you don't have any GitHub workflow to run the test. If it's okay with you, I could implement that as well.
- You do not use any linter or code formatter (e.g. flake8, black, reorder-python-imports to name the basic ones) to keep a constant code style and quality. This may also be beneficial for your code and can be used as pre-commit-hooks and in workflows. This is something that I could also implement in an additional PR (since especially the code formatter black will create a lot of non-breaking changes).

Let me know if you think this may be beneficial for pyunicore users. The APIs may also live somewhere else, not necessarily in something like a `pyunicore.helpers` module.

### CODE REVIEW

**Comment by BerndSchuller** [comment]
hi Fabian,

thank you for this work, it looks very useful to me. Having something like the job description data class is very welcome indeed. One thing I noted is that your helpers focus on username/password authentication. While that's a common way of authenticating, having an OAuth bearer token should be supported as well.
Let me know when you consider this ready for merging.

And feel free to add the other pull requests you mentioned :-) 

Thanks again, and best regards,
Bernd

**Comment by faemmi** [comment]
Hi Bernd,
thanks for your comment. That's a good note. I will implement the option to use this authentication method as well!

I will give you a note again once this PR is ready to be reviewed.

**Comment by BerndSchuller** [comment]
hi Fabian,

as you might have seen, there are a few updates in the code that kind of impact this pull request.
For one, there's a fancy integration test action now, that runs against a container with an actual UNICORE including Slurm and all the UNICORE APIs including workflow. The second sort of big change is that there is now a nicer way to deal with credentials (backwards compatible to the previous style of passing in an auth token as string).
I think the helper classes to create jobs and workflows more easily are of high general interest, the connection / authentication helpers not so much. I'd rather change the API to optionally "hide" the Transport object, ideally in a backwards compatible way...

Best regards,
Bernd

**Comment by faemmi** [comment]
Hi @BerndSchuller, I made some changes according to your comments. The PR is now ready for review.

**Comment by BerndSchuller** [comment]
Thanks Fabian! Working on it

**Comment by BerndSchuller** [comment]
It's merged. Minor change: I've removed the logging in some classes, and marked a couple fields in the job description helper as optional.
Thanks again for the contribution!

**Pull request merged**
