### PR TITLE
WIP/Proposal: return workflows sorted by time

### PR DESCRIPTION
**Pull request by schmitts**
Proposal to return workflows sorted by time.

### CODE REVIEW

**Comment by BerndSchuller** [comment]
Not a big fan of this... this makes a REST call for all the workflows in the list, which creates quite some traffic and server load if the user has many workflows. It's probably better to require the server to return the items in the order they were created.
Of course you can always filter/sort the list in your own code, if required, which is more flexible anyway.

**Comment by schmitts** [comment]
If the server can do the work, also good. Can you add a ticket?

**Comment by BerndSchuller** [comment]
https://sourceforge.net/p/unicore/issues/289/

**Comment by faemmi** [comment]
Hey @BerndSchuller, I just came across the same problem for the jobs endpoint. The jobs are returned ordered by ID, and I have to sort them manually by submission time. Has the linked issue 289 also addressed that? And if so, is this already deployed at JSC?

**Comment by BerndSchuller** [comment]
All lists coming from the server (i.e. replies o the REST API calls) should be in creation order. This has been implemented very low-level (DB select query has an "ORDER BY ..." clause, so it works the same for every type of resource (jobs, storages, etc). And as far as I can see, they are :-)
Not sure what is going on... what exactly are you doing? Which server, what client code?

**Comment by faemmi** [comment]
So, this is the response when listing the jobs with bare curl:

```bash
$ curl -X GET -H "Accept: application/json" --user '<user>:<password>' https://zam2125.zam.kfa-juelich.de:9112/JUWELS/rest/core/jobs/ | python -mjson.tool
{
    "_links": {
        "self": {
            "href": "https://zam2125.zam.kfa-juelich.de:9112/JUWELS/rest/core?offset=0&num=200"
        }
    },
    "jobs": [
        "https://zam2125.zam.kfa-juelich.de:9112/JUWELS/rest/core/jobs/1556a141-0e72-4c2d-a815-5ef076d59e04",
        "https://zam2125.zam.kfa-juelich.de:9112/JUWELS/rest/core/jobs/220276be-b76f-4730-9fd6-b54f889d07b0",
        "https://zam2125.zam.kfa-juelich.de:9112/JUWELS/rest/core/jobs/28108c54-2c9d-4080-8e9c-2fcd3e6f15cc",
        "https://zam2125.zam.kfa-juelich.de:9112/JUWELS/rest/core/jobs/331d0300-3f73-4752-a2ae-e0068676164a",
        "https://zam2125.zam.kfa-juelich.de:9112/JUWELS/rest/core/jobs/451a2e8b-1d72-4c8f-9f8f-56d63b7ee9a6",
        "https://zam2125.zam.kfa-juelich.de:9112/JUWELS/rest/core/jobs/5c515a49-20aa-4313-95c9-d5f3da7bb4cf",
        "https://zam2125.zam.kfa-juelich.de:9112/JUWELS/rest/core/jobs/63699d7a-d2d9-4e00-bc8e-8e7b4326c148",
        "https://zam2125.zam.kfa-juelich.de:9112/JUWELS/rest/core/jobs/63d90f00-b98f-4c9b-84a8-7cb65f1f7f9b",
        "https://zam2125.zam.kfa-juelich.de:9112/JUWELS/rest/core/jobs/6b6fc66d-53a0-4512-bf6a-4e5f8bc26200",
        "https://zam2125.zam.kfa-juelich.de:9112/JUWELS/rest/core/jobs/e57dd4e2-ba94-40b2-bc20-a08a39e5fb08",
        "https://zam2125.zam.kfa-juelich.de:9112/JUWELS/rest/core/jobs/e87d3fb6-cdf5-4469-93f9-6d998be5863d",
        "https://zam2125.zam.kfa-juelich.de:9112/JUWELS/rest/core/jobs/edc65dc9-3939-424a-b3c2-f212772bd9d6",
        "https://zam2125.zam.kfa-juelich.de:9112/JUWELS/rest/core/jobs/f02c10ce-d5e7-4888-b41e-906e00ee63d4"
    ]
}

# Show info for first element in jobs response.
$ curl -X GET -H "Accept: application/json" --user '<user>:<password>' https://zam2125.zam.kfa-juelich.de:9112/JUWELS/rest/core/jobs/1556a141-0e72-4c2d-a815-5ef076d59e04 | python -mjson.tool
{
    ...
    "submissionTime": "2022-11-08T10:16:55+0100",
    ...
}

# Show info for intermediate element in jobs response.
$ curl -X GET -H "Accept: application/json" --user '<user>:<password>' https://zam2125.zam.kfa-juelich.de:9112/JUWELS/rest/core/jobs/451a2e8b-1d72-4c8f-9f8f-56d63b7ee9a6 | python -mjson.tool
{
    ...
    "submissionTime": "2022-11-08T10:58:18+0100",
    ...
}

# Show info for last element in jobs response.
$ curl -X GET -H "Accept: application/json" --user '<user>:<password>' https://zam2125.zam.kfa-juelich.de:9112/JUWELS/rest/core/jobs/f02c10ce-d5e7-4888-b41e-906e00ee63d4 | python -mjson.tool
{
    "submissionTime": "2022-10-27T14:47:41+0200",
    ...
}
```
As you can see, the first, an intermediate, and the last job listed in the `/jobs` response are not in chronological order with respect to `submissionTime`. The jobs are in fact sorted alphanumerically and not with respect to `submissionTime`, which is what I would expect.

In fact, the job with the ID `451a2e8b-1d72-4c8f-9f8f-56d63b7ee9a6` is the most recent one and should appear as the first object in the `/jobs` response (as of my understanding), with the following jobs in descending order with respect to `submissionTime`.

**Comment by BerndSchuller** [comment]
yeah they definitely should be ordered. I'll investigate! In any case it is a server-side thing.

**Comment by BerndSchuller** [comment]
it's totally a server bug ;-), will fix. Could be some time until it's deployed, if it is not super-urgent (we are planning to deploy 9.0 at JSC at a convenient time, which should then also include this fix)
Thanks a lot for reporting this!

**Pull request closed without merging**
